# Generated by Django 2.2.15 on 2023-01-25 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('followup', '__first__'),
        ('operation', '__first__'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentDate', models.DateField(blank=True, null=True)),
                ('appointmentType', models.CharField(blank=True, choices=[('New Visit', 'New Visit'), ('Repeat', 'Repeat'), ('Consultation', 'Consultation'), ('Follow up', 'Follow up'), ('Operative', 'Operative')], max_length=20)),
                ('appointmentStatus', models.CharField(blank=True, choices=[('Waiting', 'Waiting'), ('On going', 'On going'), ('Done', 'Done'), ('Cancel', 'Cancel')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followup', models.ManyToManyField(to='followup.Followup')),
                ('operation', models.ManyToManyField(to='operation.Operation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='patient.Patient')),
            ],
            options={
                'ordering': ('-appointmentDate',),
            },
        ),
    ]
