# Generated by Django 2.1.5 on 2022-08-06 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cause', '0001_initial'),
        ('diagnose', '0001_initial'),
        ('investigation', '0001_initial'),
        ('patient', '0001_initial'),
        ('treatment', '0001_initial'),
        ('referrer', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentDate', models.DateField(blank=True, null=True)),
                ('appointmentType', models.CharField(blank=True, choices=[('N', 'New Visit'), ('R', 'Repeat'), ('C', 'Consultation'), ('F', 'Follow up'), ('O', 'Operative')], max_length=1)),
                ('appointmentStatus', models.CharField(blank=True, choices=[('W', 'Waiting'), ('O', 'On going'), ('D', 'Done'), ('C', 'Cancel')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cause', models.ManyToManyField(blank=True, null=True, to='cause.Cause')),
                ('diagnose', models.ManyToManyField(blank=True, null=True, to='diagnose.Diagnose')),
                ('investigation', models.ManyToManyField(blank=True, null=True, to='investigation.Investigation')),
                ('operation', models.ManyToManyField(blank=True, null=True, to='operation.Operation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
                ('referrer', models.ManyToManyField(blank=True, null=True, to='referrer.Referrer')),
                ('treatment', models.ManyToManyField(blank=True, null=True, to='treatment.Treatment')),
            ],
        ),
    ]
