# Generated by Django 2.2.15 on 2023-01-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newVisit', '0001_initial'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='new_visit',
            field=models.ManyToManyField(to='newVisit.NewVisit'),
        ),
    ]
