# Generated by Django 2.1.5 on 2022-08-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cause',
            field=models.ManyToManyField(blank=True, to='cause.Cause'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='diagnose',
            field=models.ManyToManyField(blank=True, to='diagnose.Diagnose'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='investigation',
            field=models.ManyToManyField(blank=True, to='investigation.Investigation'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='operation',
            field=models.ManyToManyField(blank=True, to='operation.Operation'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='referrer',
            field=models.ManyToManyField(blank=True, to='referrer.Referrer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='treatment',
            field=models.ManyToManyField(blank=True, to='treatment.Treatment'),
        ),
    ]
