# Generated by Django 2.2.15 on 2022-08-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20220818_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentStatus',
            field=models.CharField(blank=True, choices=[('Waiting', 'Waiting'), ('On going', 'On going'), ('Done', 'Done'), ('Cancel', 'Cancel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentType',
            field=models.CharField(blank=True, choices=[('New Visit', 'New Visit'), ('Repeat', 'Repeat'), ('Consultation', 'Consultation'), ('Follow up', 'Follow up'), ('Operative', 'Operative')], max_length=20),
        ),
    ]
