# Generated by Django 2.2.15 on 2022-08-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20220820_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='operation',
            field=models.ManyToManyField(to='operation.Operation'),
        ),
    ]
