# Generated by Django 4.1.2 on 2022-10-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0001_initial'),
        ('appointment', '0008_auto_20220825_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='followup',
            field=models.ManyToManyField(to='followup.followup'),
        ),
    ]
