# Generated by Django 2.1.5 on 2022-08-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
