# Generated by Django 2.2.15 on 2022-12-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='patient',
        #     name='yasser',
        # ),
    ]
