# Generated by Django 2.1.5 on 2022-08-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_investigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='yORm',
            field=models.CharField(blank=True, choices=[('Y', 'Year'), ('M', 'Month')], max_length=1),
        ),
    ]
