# Generated by Django 2.1.5 on 2022-08-06 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_remove_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='referredFrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referrer.Referrer'),
        ),
    ]
