# Generated by Django 2.1.5 on 2022-08-07 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_remove_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='yORm',
        ),
    ]
