# Generated by Django 2.2.15 on 2022-08-16 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cause', '0001_initial'),
        ('patient', '0009_remove_patient_yorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cause.Cause'),
        ),
    ]
