# Generated by Django 2.2.15 on 2022-08-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cause', '0001_initial'),
        ('patient', '0010_patient_cause'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='cause',
        ),
        migrations.AddField(
            model_name='patient',
            name='cause',
            field=models.ManyToManyField(blank=True, to='cause.Cause'),
        ),
    ]
