# Generated by Django 2.2.15 on 2022-08-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0001_initial'),
        ('treatment', '0001_initial'),
        ('patient', '0011_auto_20220816_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diagnose',
            field=models.ManyToManyField(blank=True, to='diagnose.Diagnose'),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment',
            field=models.ManyToManyField(blank=True, to='treatment.Treatment'),
        ),
    ]
