# Generated by Django 2.2.15 on 2022-08-16 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_auto_20220816_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='diagnose',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='treatment',
        ),
    ]
