# Generated by Django 2.2.15 on 2022-08-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
        ('diagnose', '0001_initial'),
        ('investigation', '0001_initial'),
        ('patient', '0013_auto_20220816_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diagnose',
            field=models.ManyToManyField(blank=True, to='diagnose.Diagnose'),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment',
            field=models.ManyToManyField(blank=True, to='treatment.Treatment'),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='investigation',
        ),
        migrations.AddField(
            model_name='patient',
            name='investigation',
            field=models.ManyToManyField(blank=True, to='investigation.Investigation'),
        ),
    ]
