# Generated by Django 2.2.15 on 2022-08-16 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_auto_20220816_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='diagnose',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='investigation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='treatment',
        ),
    ]
