# Generated by Django 2.2.15 on 2022-08-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0001_initial'),
        ('patient', '0016_patient_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diagnose',
            field=models.ManyToManyField(blank=True, to='diagnose.Diagnose'),
        ),
    ]
