# Generated by Django 2.2.15 on 2022-08-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
        ('investigation', '0001_initial'),
        ('patient', '0017_patient_diagnose'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='investigation',
            field=models.ManyToManyField(blank=True, to='investigation.Investigation'),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment',
            field=models.ManyToManyField(blank=True, to='treatment.Treatment'),
        ),
    ]
