# Generated by Django 2.2.15 on 2022-08-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_auto_20220816_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cause',
            field=models.ManyToManyField(blank=True, null=True, to='cause.Cause'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnose',
            field=models.ManyToManyField(blank=True, null=True, to='diagnose.Diagnose'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='investigation',
            field=models.ManyToManyField(blank=True, null=True, to='investigation.Investigation'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientAddress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phoneNumber',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatment',
            field=models.ManyToManyField(blank=True, null=True, to='treatment.Treatment'),
        ),
    ]
