# Generated by Django 2.2.15 on 2022-08-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_auto_20220823_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cause',
            field=models.ManyToManyField(blank=True, to='cause.Cause'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnose',
            field=models.ManyToManyField(blank=True, to='diagnose.Diagnose'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='investigation',
            field=models.ManyToManyField(blank=True, to='investigation.Investigation'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatment',
            field=models.ManyToManyField(blank=True, to='treatment.Treatment'),
        ),
    ]
