# Generated by Django 2.2.15 on 2022-08-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrer', '0001_initial'),
        ('patient', '0021_auto_20220823_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='referredFrom',
        ),
        migrations.AddField(
            model_name='patient',
            name='referredFrom',
            field=models.ManyToManyField(blank=True, to='referrer.Referrer'),
        ),
    ]
