# Generated by Django 4.1 on 2022-09-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_auto_20220824_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patientComplaint',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
