# Generated by Django 4.1 on 2022-09-12 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0024_remove_patient_attachment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_attachments', to='patient.patient'),
        ),
    ]
